kind: pipeline
name: default
type: docker

steps:
  - name: test
    image: python:latest
    commands:
      - apt-get update -y && apt-get upgrade -y
      - apt-get install -y npm
      - python -m pip install --upgrade pip
      - cd src
      - pip install -r requirements/production.txt
      - pip install pytest
      - sh ./install.sh
      - cd ..
      - export PYTHONPATH=".:src/"
      - pytest

  - name: deploy-trigger
    image: plugins/downstream
    settings:
      server: https://drone.mylassi.xyz
      token:
        from_secret: drone-token
      fork: true
      repositories:
        - lassi/NSSLFlaskWebApp.Deploy@master
    when:
      branch:
      - master
